### ISSUE TITLE
Поддержка светодиодной ленты

### ISSUE THREAD

**Issue by perfect-deform** [altfoxie/ha-sberdevices#4]
Здравствуйте, подскажите пожалуйста, а можно ли добавить таким же образом светодиодную ленту?
Работает она так же как и лампочка, свойства те же.

Пока докинул свой костыль в ваш :D
```
if "bulb" in device["image_set_type"] or "ledstrip" in device["image_set_type"]
```

**Comment by altfoxie** [comment]
Привет! Заказал ленту, посмотрю что можно сделать

**Comment by altfoxie** [comment]
У ленты действительно те же свойства, что и у лампы. Твой костыль теперь тоже в коде)
