### ISSUE TITLE
Этот объект больше не предоставляется интеграцией sberdevices

### ISSUE THREAD

**Issue by taziy** [altfoxie/ha-sberdevices#5]
Добрый день. Выходит вон такая ошибка. Может кно нибудь подскажет как её решить?
"Этот объект больше не предоставляется интеграцией sberdevices. Вы можете удалить его на вкладке "Настройки", если он больше не будет использоваться."

**Comment by altfoxie** [comment]
Должно быть исправлено последним изменением 🤔
