### ISSUE TITLE
После последнего обновления HA больше не работает

### ISSUE THREAD

**Issue by digitizer77** [altfoxie/ha-sberdevices#6]
Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble

**Comment by l31313** [comment]
Измени в manifest.json 
"requirements": ["httpx==0.26.0", "Authlib==1.2.1"], 
на 
"requirements": ["httpx==0.27.0", "Authlib==1.2.1"],

**Comment by digitizer77** [comment]
Огромное спасибо. Помогло. Все работает

**Comment by digitizer77** [comment]
Огромное спасибо. Помогло. Все работает
