### ISSUE TITLE
Не работает управление лентами

### ISSUE THREAD

**Issue by daydreamer1982** [altfoxie/ha-sberdevices#9]
Здравствуйте, установил и подключил интеграцию, всё отлично работает, лампочки включаются и выключаются, цвети и температура меняется, всё отлично. Но вот светодиодные ленты только отображают статус, а при нажатии на переключатель в Home assistant лента не реагирует.  Можно ли это как-то исправить?

**Comment by altfoxie** [comment]
Привет! Уточни, пожалуйста, что за модель ленты?

**Comment by daydreamer1982** [comment]
Ленты покупал в одинаковых коробках но в Home assistant у той, которую покупал первой, в описании устройства написано SMART LED STRIP -2 Tuya, а ещё у двух SBDV-00055 Sber
![Снимок экрана 2024-07-31 153428](https://github.com/user-attachments/assets/b1144cd6-b838-48a8-ab95-a577523bc6e8)
![Снимок экрана 2024-07-31 153350](https://github.com/user-attachments/assets/b7073b98-ef6d-4810-9ee9-c907e8646ee4)

**Comment by daydreamer1982** [comment]
Странное дело, обновил Home assistant и всё заработало. Спасибо за ответы
